version: '3.3'

services:
  api_gateway:   # This is the Amazon Reviews Service
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api_gateway
    container_name: api_gateway_container
    ports:
      - "8000:8000"
    environment:
      - MARKET_PERF_HOST=market_performance_container
    networks:
      - microservices

  market_performance:
    build:
      context: ./app/microservices/market-performance
      dockerfile: Dockerfile
    image: market_performance
    container_name: market_performance_container
    ports:
      - "50053:50053"
    networks:
      - microservices

  question_analysis:
    build:
      context: ./app/microservices/question-analysis
      dockerfile: Dockerfile
    image: question_analysis
    container_name: question_analysis_container
    ports:
      - "50055:50055"
      
  yelp_reviews:
    build:
      context: ./app/microservices/yelp-reviews
      dockerfile: Dockerfile
    image: yelp_reviews
    container_name: yelp_reviews_container
    ports:
      - "5001:5000"
    networks:
      - microservices

  nginx_gateway:
    image: nginx:latest
    container_name: nginx_gateway_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api_gateway
      - yelp_reviews
    networks:
      - microservices

networks:
  microservices: 
