apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-svc
  labels:
    app: sentiment-analysis
spec:
  selector:
    app: sentiment-analysis
  ports:
    - protocol: TCP
      port: 50056  # The port the service is exposed on within the cluster
      targetPort: 50056  # The port the container is listening on
  type: ClusterIP
