apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'microservices'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: default
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: (api-gateway|market-analysis|nginx-gateway|question-analysis|yelp-reviews)
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: http
            