scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['localhost:9090']
  
    - job_name: py-prom-s
      scrape_interval: 5s
      static_configs:
        - targets: ['py-prom-s:8000']

