apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: market-analysis-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: market-analysis-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50