# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market-performance.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18market-performance.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x9a\x01\n\x19GetProductMetadataRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\r\n\x05\x62rand\x18\x02 \x01(\t\x12-\n\x08minPrice\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.FloatValue\x12-\n\x08maxPrice\x18\x04 \x01(\x0b\x32\x1b.google.protobuf.FloatValue\"8\n\x1aGetProductMetadataResponse\x12\x1a\n\x08products\x18\x01 \x03(\x0b\x32\x08.Product\"\x1a\n\x18GetMainCategoriesRequest\"3\n\x19GetMainCategoriesResponse\x12\x16\n\x0emainCategories\x18\x01 \x03(\t\")\n\x15GetTopProductsRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\"7\n\x16GetTopProductsResponse\x12\x1d\n\x0btopProducts\x18\x01 \x03(\x0b\x32\x08.Product\"&\n\x12GetTopBrandRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\"6\n\x13GetTopBrandResponse\x12\x10\n\x08topBrand\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"X\n\x07Product\x12\r\n\x05title\x18\x01 \x01(\t\x12\r\n\x05\x62rand\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x0c\n\x04rank\x18\x04 \x01(\t\x12\x12\n\ncategories\x18\x05 \x03(\t2\xb2\x02\n\x18MarketPerformanceService\x12M\n\x12GetProductMetadata\x12\x1a.GetProductMetadataRequest\x1a\x1b.GetProductMetadataResponse\x12J\n\x11GetMainCategories\x12\x19.GetMainCategoriesRequest\x1a\x1a.GetMainCategoriesResponse\x12\x41\n\x0eGetTopProducts\x12\x16.GetTopProductsRequest\x1a\x17.GetTopProductsResponse\x12\x38\n\x0bGetTopBrand\x12\x13.GetTopBrandRequest\x1a\x14.GetTopBrandResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_performance_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETPRODUCTMETADATAREQUEST']._serialized_start=61
  _globals['_GETPRODUCTMETADATAREQUEST']._serialized_end=215
  _globals['_GETPRODUCTMETADATARESPONSE']._serialized_start=217
  _globals['_GETPRODUCTMETADATARESPONSE']._serialized_end=273
  _globals['_GETMAINCATEGORIESREQUEST']._serialized_start=275
  _globals['_GETMAINCATEGORIESREQUEST']._serialized_end=301
  _globals['_GETMAINCATEGORIESRESPONSE']._serialized_start=303
  _globals['_GETMAINCATEGORIESRESPONSE']._serialized_end=354
  _globals['_GETTOPPRODUCTSREQUEST']._serialized_start=356
  _globals['_GETTOPPRODUCTSREQUEST']._serialized_end=397
  _globals['_GETTOPPRODUCTSRESPONSE']._serialized_start=399
  _globals['_GETTOPPRODUCTSRESPONSE']._serialized_end=454
  _globals['_GETTOPBRANDREQUEST']._serialized_start=456
  _globals['_GETTOPBRANDREQUEST']._serialized_end=494
  _globals['_GETTOPBRANDRESPONSE']._serialized_start=496
  _globals['_GETTOPBRANDRESPONSE']._serialized_end=550
  _globals['_PRODUCT']._serialized_start=552
  _globals['_PRODUCT']._serialized_end=640
  _globals['_MARKETPERFORMANCESERVICE']._serialized_start=643
  _globals['_MARKETPERFORMANCESERVICE']._serialized_end=949
# @@protoc_insertion_point(module_scope)
