apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: yelp-reviews-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yelp-reviews-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50