# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reviews.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreviews.proto\"\xbd\x01\n\x06Review\x12\x0e\n\x06rating\x18\x01 \x01(\x02\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x0e\n\x06images\x18\x04 \x01(\t\x12\x0c\n\x04\x61sin\x18\x05 \x01(\t\x12\x13\n\x0bparent_asin\x18\x06 \x01(\t\x12\x0f\n\x07user_id\x18\x07 \x01(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\x03\x12\x19\n\x11verified_purchase\x18\t \x01(\x08\x12\x14\n\x0chelpful_vote\x18\n \x01(\x03\".\n\x13\x43reateReviewRequest\x12\x17\n\x06review\x18\x01 \x01(\x0b\x32\x07.Review\"/\n\x14\x43reateReviewResponse\x12\x17\n\x06review\x18\x01 \x01(\x0b\x32\x07.Review\"&\n\x11ReadReviewRequest\x12\x11\n\treview_id\x18\x01 \x01(\t\"-\n\x12ReadReviewResponse\x12\x17\n\x06review\x18\x01 \x01(\x0b\x32\x07.Review\"A\n\x13UpdateReviewRequest\x12\x11\n\treview_id\x18\x01 \x01(\t\x12\x17\n\x06review\x18\x02 \x01(\x0b\x32\x07.Review\"/\n\x14UpdateReviewResponse\x12\x17\n\x06review\x18\x01 \x01(\x0b\x32\x07.Review\"(\n\x13\x44\x65leteReviewRequest\x12\x11\n\treview_id\x18\x01 \x01(\t\"\'\n\x14\x44\x65leteReviewResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xfd\x01\n\rReviewService\x12;\n\x0c\x43reateReview\x12\x14.CreateReviewRequest\x1a\x15.CreateReviewResponse\x12\x35\n\nReadReview\x12\x12.ReadReviewRequest\x1a\x13.ReadReviewResponse\x12;\n\x0cUpdateReview\x12\x14.UpdateReviewRequest\x1a\x15.UpdateReviewResponse\x12;\n\x0c\x44\x65leteReview\x12\x14.DeleteReviewRequest\x1a\x15.DeleteReviewResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reviews_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REVIEW']._serialized_start=18
  _globals['_REVIEW']._serialized_end=207
  _globals['_CREATEREVIEWREQUEST']._serialized_start=209
  _globals['_CREATEREVIEWREQUEST']._serialized_end=255
  _globals['_CREATEREVIEWRESPONSE']._serialized_start=257
  _globals['_CREATEREVIEWRESPONSE']._serialized_end=304
  _globals['_READREVIEWREQUEST']._serialized_start=306
  _globals['_READREVIEWREQUEST']._serialized_end=344
  _globals['_READREVIEWRESPONSE']._serialized_start=346
  _globals['_READREVIEWRESPONSE']._serialized_end=391
  _globals['_UPDATEREVIEWREQUEST']._serialized_start=393
  _globals['_UPDATEREVIEWREQUEST']._serialized_end=458
  _globals['_UPDATEREVIEWRESPONSE']._serialized_start=460
  _globals['_UPDATEREVIEWRESPONSE']._serialized_end=507
  _globals['_DELETEREVIEWREQUEST']._serialized_start=509
  _globals['_DELETEREVIEWREQUEST']._serialized_end=549
  _globals['_DELETEREVIEWRESPONSE']._serialized_start=551
  _globals['_DELETEREVIEWRESPONSE']._serialized_end=590
  _globals['_REVIEWSERVICE']._serialized_start=593
  _globals['_REVIEWSERVICE']._serialized_end=846
# @@protoc_insertion_point(module_scope)
