apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-analysis-deployment
  labels:
    app: question-analysis
spec:
  replicas: 1  # Adjust the number of replicas based on your traffic needs
  selector:
    matchLabels:
      app: question-analysis
  template:
    metadata:
      labels:
        app: question-analysis
    spec:
      containers:
        - name: question-analysis
          image: gcr.io/cloudcomputinginc/question_analysis:latest  # path to image in GCR
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: gcr-io
          # Environment variables, if needed, go here
          # env:
          # - name: ENV_VAR_NAME
          #   value: "value"
